language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: JgDmwjacxp0Yxk0MEaEym4RkpELgRQ1R8v1QGN2soTLX5kh3Wj2O/oaJaYgrqtBfhhYEC0pRJq1WhvARGJk1lTONxUBJD4f+TfLRPJAE5rItuocrfmrlXonwFM8t65PDav6WdzLbFdQKUuYNycZfQn/HLUjC5IHjhXBrtlufaAPJtzu1KJcKCJeatYbctz1smW0eZc1YMmSdGpayIKr39+GpwvqplmDr5GBZP7D0gJqgVq4F7aXgI2hbSLBRopRsI2gxW7+1acrn0Pv/dHyu8cKjbgGVEt63zB/xA0Vx2fbamQUVLDFn/aqN3vNs3jIoeCK0oo35JefORtppFsdH5hgWbjrbfiLvXJknajVxKJY1eErutu43l3bIxvxnuD+IPky1Dtnq+Obtf47HVDSswlKvP8h2zB2MS4hAsvSNftA8d0cRqh993NY+QAm8kJJE1OwjKmVUMk4fg+A5zNcJPR+rBgpskKxoexJYmdIK6HMPbuUsTRdkZBJac3ShZt+nMq/FPArYxA8jsVAPUxh3eOF+dr6IELiXBysbz8HTDCaCYeszzdJX/4OxpTJMwgVNg6jmY4tpmI+oPupt/3bWeIi7zEPkP6aanxuWjRjV6T5UtFJ8tDcasV9Re8AeDosHk/IkgJJ3VJy8vZO3Wros4mUb9CYOiASLgsDov6z9feE=
  app: https://murmuring-shore-60848.herokuapp.com/
